site_name: "[Seu Projeto de Data Science]"
repo_url: https://github.com/mgrb/data-science-boilerplate
repo_name: mgrb/data-science-boilerplate

# Theme
theme:
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.sections
        - content.code.copy
    palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Markdown extensions
markdown_extensions:
    - abbr
    - attr_list
    - toc:
        permalink: true
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.smartsymbols
    - pymdownx.tilde
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.blocks.admonition
    - pymdownx.tabbed:
        alternate_style: true
    - tables
